export const dummyUsers = [
  {
    id: 1,
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    matchPercentage: 95,
    commonTags: ['AI Development', 'Machine Learning', 'Data Science'],
    bio: 'AI researcher specializing in deep learning and computer vision',
    lastActive: '2 minutes ago',
    isTopRanked: true,
  },
  {
    id: 2,
    name: 'Michael Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    matchPercentage: 88,
    commonTags: ['Web Development', 'UI/UX Design', 'React'],
    bio: 'Full-stack developer with a passion for creating beautiful user experiences',
    lastActive: '5 minutes ago',
    isTopRanked: false,
  },
  {
    id: 3,
    name: 'Emily Johnson',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    matchPercentage: 85,
    commonTags: ['Product Management', 'Agile', 'Strategy'],
    bio: 'Product manager focused on building user-centric solutions',
    lastActive: '15 minutes ago',
    isTopRanked: false,
  },
  {
    id: 4,
    name: 'David Kim',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    matchPercentage: 82,
    commonTags: ['Mobile Development', 'iOS', 'Swift'],
    bio: 'iOS developer creating intuitive mobile experiences',
    lastActive: '1 hour ago',
    isTopRanked: false,
  },
  {
    id: 5,
    name: 'Lisa Patel',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    matchPercentage: 78,
    commonTags: ['Cloud Architecture', 'AWS', 'DevOps'],
    bio: 'Cloud architect with expertise in scalable systems',
    lastActive: '2 hours ago',
    isTopRanked: false,
  },
];

export const currentUser = {
  id: 'current',
  name: 'Alex Morgan',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
  bio: 'Senior Full Stack Developer passionate about building scalable applications and mentoring others',
  commonTags: ['Full Stack', 'React', 'Node.js', 'Cloud Architecture', 'Mentoring'],
  lastActive: 'Online',
  isTopRanked: true,
};